#!/bin/bash

url="$1"
cookies="$2"

curl "http://$1"                                                                          \
  -H "Cookie: $2"                                                                         \
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"     \
  -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
  -H "Accept-Language: en-US,en;q=0.5"
